language: cpp

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libxerces-c-dev libtinyxml-dev swig python3-dev python3-pytest

script:
 - export CC=gcc-6
 - export CXX=g++-6
 - export GCOV=gcov-6
 - cmake -DENABLE_COVERAGE=yes .
 - build-wrapper-linux-x86-64 --out-dir bw-output make clean all || true  # may fail in builds from forks
 - make && ctest -V
 - make gcov
 - sonar-scanner || true  # may fail in builds from forks

after_success:
 - curl -s https://codecov.io/bash > cov.sh && bash cov.sh -x "$GCOV"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

  sonarcloud:
    organization: "openscap"

  coverity_scan:
    project:
      name: "OpenSCAP/libswid"
      description: "SWID tags library"
    notification_email: matyc@redhat.com
    build_command_prepend: "export CC=gcc-6 CXX=g++-6; cov-configure --comptype g++ --compiler g++-6 --template; cmake ."
    build_command: make
    branch_pattern: master

cache:
  directories:
    - '$HOME/.sonar/cache'
