coverage:
  precision: 2
  round: nearest
  range: "60...100"
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        target: 80%

coverage:
  ignore:
    - "test/"

comment:
  layout: "header, diff"
  require_changes: false
  behavior: default
