coverage:
  precision: 2
  round: nearest
  range: "60...100"
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        threshold: 2%
  ignore:
    - "test/"

comment:
  behavior: default
